FROM golang:1-alpine3.10 as builder

RUN apk add git
RUN go get github.com/urfave/cli

COPY src .

# FROM golang:1-alpine3.10 as stage-comment

FROM golang:1-alpine3.10 as test

CMD ["go", "run", "main_test.go"]

FROM alpine3
COPY --from=builder build /build
